
name: Node.js and React App Deployment

on:
  push:
    branches:
      - main  # Adjust the branch as needed

jobs:
  deploy:
    runs-on: ubuntu-latest  # You can change the OS based on your EC2 instance

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 14

    - name: Install Dependencies
      run: |
        npm install

    - name: Build React App
      run: |
        npm run build

    - name: Copy Code to EC2
      run: |
        scp -o StrictHostKeyChecking=no -i path/to/your-key.pem -r path/to/your-repo-directory ec2-user@your-instance-ip:~/

    - name: SSH into EC2
      run: |
        ssh -i path/to/your-key.pem ec2-user@your-instance-ip 'mv ~/your-repo-directory /path/to/your-app-directory'

    - name: Setup Node.js on EC2
      run: |
        ssh -i path/to/your-key.pem ec2-user@your-instance-ip 'curl -fsSL https://deb.nodesource.com/setup_14.x | sudo -E bash -'
        ssh -i path/to/your-key.pem ec2-user@your-instance-ip 'sudo apt-get install -y nodejs'

    - name: Install Dependencies on EC2
      run: |
        ssh -i path/to/your-key.pem ec2-user@your-instance-ip 'cd /path/to/your-app-directory && npm install'

    - name: Start Node.js Server on EC2
      run: |
        ssh -i path/to/your-key.pem ec2-user@your-instance-ip 'cd /path/to/your-app-directory && npm start'

    # Add additional steps for optional configurations, Nginx setup, etc.
